// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: query.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_query_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_query_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_query_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_query_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_query_2eproto;
class QueryRequest;
struct QueryRequestDefaultTypeInternal;
extern QueryRequestDefaultTypeInternal _QueryRequest_default_instance_;
class QueryResponse;
struct QueryResponseDefaultTypeInternal;
extern QueryResponseDefaultTypeInternal _QueryResponse_default_instance_;
class SetEfRequest;
struct SetEfRequestDefaultTypeInternal;
extern SetEfRequestDefaultTypeInternal _SetEfRequest_default_instance_;
class SetEfResponse;
struct SetEfResponseDefaultTypeInternal;
extern SetEfResponseDefaultTypeInternal _SetEfResponse_default_instance_;
class UpdateIndexRequest;
struct UpdateIndexRequestDefaultTypeInternal;
extern UpdateIndexRequestDefaultTypeInternal _UpdateIndexRequest_default_instance_;
class VectorData;
struct VectorDataDefaultTypeInternal;
extern VectorDataDefaultTypeInternal _VectorData_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::QueryRequest* Arena::CreateMaybeMessage<::QueryRequest>(Arena*);
template<> ::QueryResponse* Arena::CreateMaybeMessage<::QueryResponse>(Arena*);
template<> ::SetEfRequest* Arena::CreateMaybeMessage<::SetEfRequest>(Arena*);
template<> ::SetEfResponse* Arena::CreateMaybeMessage<::SetEfResponse>(Arena*);
template<> ::UpdateIndexRequest* Arena::CreateMaybeMessage<::UpdateIndexRequest>(Arena*);
template<> ::VectorData* Arena::CreateMaybeMessage<::VectorData>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class QueryRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:QueryRequest) */ {
 public:
  inline QueryRequest() : QueryRequest(nullptr) {}
  ~QueryRequest() override;
  explicit PROTOBUF_CONSTEXPR QueryRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  QueryRequest(const QueryRequest& from);
  QueryRequest(QueryRequest&& from) noexcept
    : QueryRequest() {
    *this = ::std::move(from);
  }

  inline QueryRequest& operator=(const QueryRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline QueryRequest& operator=(QueryRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const QueryRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const QueryRequest* internal_default_instance() {
    return reinterpret_cast<const QueryRequest*>(
               &_QueryRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(QueryRequest& a, QueryRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(QueryRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(QueryRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  QueryRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<QueryRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const QueryRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const QueryRequest& from) {
    QueryRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(QueryRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "QueryRequest";
  }
  protected:
  explicit QueryRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kVectorFieldNumber = 1,
    kKFieldNumber = 2,
  };
  // repeated float vector = 1;
  int vector_size() const;
  private:
  int _internal_vector_size() const;
  public:
  void clear_vector();
  private:
  float _internal_vector(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_vector() const;
  void _internal_add_vector(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_vector();
  public:
  float vector(int index) const;
  void set_vector(int index, float value);
  void add_vector(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      vector() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_vector();

  // int32 k = 2;
  void clear_k();
  int32_t k() const;
  void set_k(int32_t value);
  private:
  int32_t _internal_k() const;
  void _internal_set_k(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:QueryRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > vector_;
    int32_t k_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_query_2eproto;
};
// -------------------------------------------------------------------

class QueryResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:QueryResponse) */ {
 public:
  inline QueryResponse() : QueryResponse(nullptr) {}
  ~QueryResponse() override;
  explicit PROTOBUF_CONSTEXPR QueryResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  QueryResponse(const QueryResponse& from);
  QueryResponse(QueryResponse&& from) noexcept
    : QueryResponse() {
    *this = ::std::move(from);
  }

  inline QueryResponse& operator=(const QueryResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline QueryResponse& operator=(QueryResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const QueryResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const QueryResponse* internal_default_instance() {
    return reinterpret_cast<const QueryResponse*>(
               &_QueryResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(QueryResponse& a, QueryResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(QueryResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(QueryResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  QueryResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<QueryResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const QueryResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const QueryResponse& from) {
    QueryResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(QueryResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "QueryResponse";
  }
  protected:
  explicit QueryResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLabelsFieldNumber = 1,
    kDistancesFieldNumber = 2,
  };
  // repeated int32 labels = 1;
  int labels_size() const;
  private:
  int _internal_labels_size() const;
  public:
  void clear_labels();
  private:
  int32_t _internal_labels(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      _internal_labels() const;
  void _internal_add_labels(int32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      _internal_mutable_labels();
  public:
  int32_t labels(int index) const;
  void set_labels(int index, int32_t value);
  void add_labels(int32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
      labels() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
      mutable_labels();

  // repeated float distances = 2;
  int distances_size() const;
  private:
  int _internal_distances_size() const;
  public:
  void clear_distances();
  private:
  float _internal_distances(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_distances() const;
  void _internal_add_distances(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_distances();
  public:
  float distances(int index) const;
  void set_distances(int index, float value);
  void add_distances(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      distances() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_distances();

  // @@protoc_insertion_point(class_scope:QueryResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t > labels_;
    mutable std::atomic<int> _labels_cached_byte_size_;
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > distances_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_query_2eproto;
};
// -------------------------------------------------------------------

class SetEfRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:SetEfRequest) */ {
 public:
  inline SetEfRequest() : SetEfRequest(nullptr) {}
  ~SetEfRequest() override;
  explicit PROTOBUF_CONSTEXPR SetEfRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SetEfRequest(const SetEfRequest& from);
  SetEfRequest(SetEfRequest&& from) noexcept
    : SetEfRequest() {
    *this = ::std::move(from);
  }

  inline SetEfRequest& operator=(const SetEfRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline SetEfRequest& operator=(SetEfRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SetEfRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const SetEfRequest* internal_default_instance() {
    return reinterpret_cast<const SetEfRequest*>(
               &_SetEfRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(SetEfRequest& a, SetEfRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(SetEfRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SetEfRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SetEfRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SetEfRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SetEfRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SetEfRequest& from) {
    SetEfRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SetEfRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "SetEfRequest";
  }
  protected:
  explicit SetEfRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kEfSearchFieldNumber = 1,
  };
  // int32 ef_search = 1;
  void clear_ef_search();
  int32_t ef_search() const;
  void set_ef_search(int32_t value);
  private:
  int32_t _internal_ef_search() const;
  void _internal_set_ef_search(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:SetEfRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t ef_search_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_query_2eproto;
};
// -------------------------------------------------------------------

class SetEfResponse final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:SetEfResponse) */ {
 public:
  inline SetEfResponse() : SetEfResponse(nullptr) {}
  ~SetEfResponse() override;
  explicit PROTOBUF_CONSTEXPR SetEfResponse(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SetEfResponse(const SetEfResponse& from);
  SetEfResponse(SetEfResponse&& from) noexcept
    : SetEfResponse() {
    *this = ::std::move(from);
  }

  inline SetEfResponse& operator=(const SetEfResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline SetEfResponse& operator=(SetEfResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SetEfResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const SetEfResponse* internal_default_instance() {
    return reinterpret_cast<const SetEfResponse*>(
               &_SetEfResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(SetEfResponse& a, SetEfResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(SetEfResponse* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SetEfResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SetEfResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<SetEfResponse>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SetEfResponse& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const SetEfResponse& from) {
    SetEfResponse::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SetEfResponse* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "SetEfResponse";
  }
  protected:
  explicit SetEfResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStatusFieldNumber = 1,
    kNewEfSearchFieldNumber = 2,
  };
  // string status = 1;
  void clear_status();
  const std::string& status() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_status(ArgT0&& arg0, ArgT... args);
  std::string* mutable_status();
  PROTOBUF_NODISCARD std::string* release_status();
  void set_allocated_status(std::string* status);
  private:
  const std::string& _internal_status() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_status(const std::string& value);
  std::string* _internal_mutable_status();
  public:

  // int32 new_ef_search = 2;
  void clear_new_ef_search();
  int32_t new_ef_search() const;
  void set_new_ef_search(int32_t value);
  private:
  int32_t _internal_new_ef_search() const;
  void _internal_set_new_ef_search(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:SetEfResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr status_;
    int32_t new_ef_search_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_query_2eproto;
};
// -------------------------------------------------------------------

class VectorData final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:VectorData) */ {
 public:
  inline VectorData() : VectorData(nullptr) {}
  ~VectorData() override;
  explicit PROTOBUF_CONSTEXPR VectorData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  VectorData(const VectorData& from);
  VectorData(VectorData&& from) noexcept
    : VectorData() {
    *this = ::std::move(from);
  }

  inline VectorData& operator=(const VectorData& from) {
    CopyFrom(from);
    return *this;
  }
  inline VectorData& operator=(VectorData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const VectorData& default_instance() {
    return *internal_default_instance();
  }
  static inline const VectorData* internal_default_instance() {
    return reinterpret_cast<const VectorData*>(
               &_VectorData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(VectorData& a, VectorData& b) {
    a.Swap(&b);
  }
  inline void Swap(VectorData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VectorData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  VectorData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<VectorData>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const VectorData& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const VectorData& from) {
    VectorData::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(VectorData* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "VectorData";
  }
  protected:
  explicit VectorData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kVectorFieldNumber = 2,
    kIdFieldNumber = 1,
  };
  // repeated float vector = 2;
  int vector_size() const;
  private:
  int _internal_vector_size() const;
  public:
  void clear_vector();
  private:
  float _internal_vector(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_vector() const;
  void _internal_add_vector(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_vector();
  public:
  float vector(int index) const;
  void set_vector(int index, float value);
  void add_vector(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      vector() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_vector();

  // int64 id = 1;
  void clear_id();
  int64_t id() const;
  void set_id(int64_t value);
  private:
  int64_t _internal_id() const;
  void _internal_set_id(int64_t value);
  public:

  // @@protoc_insertion_point(class_scope:VectorData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > vector_;
    int64_t id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_query_2eproto;
};
// -------------------------------------------------------------------

class UpdateIndexRequest final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:UpdateIndexRequest) */ {
 public:
  inline UpdateIndexRequest() : UpdateIndexRequest(nullptr) {}
  ~UpdateIndexRequest() override;
  explicit PROTOBUF_CONSTEXPR UpdateIndexRequest(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  UpdateIndexRequest(const UpdateIndexRequest& from);
  UpdateIndexRequest(UpdateIndexRequest&& from) noexcept
    : UpdateIndexRequest() {
    *this = ::std::move(from);
  }

  inline UpdateIndexRequest& operator=(const UpdateIndexRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline UpdateIndexRequest& operator=(UpdateIndexRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const UpdateIndexRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const UpdateIndexRequest* internal_default_instance() {
    return reinterpret_cast<const UpdateIndexRequest*>(
               &_UpdateIndexRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(UpdateIndexRequest& a, UpdateIndexRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(UpdateIndexRequest* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(UpdateIndexRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  UpdateIndexRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<UpdateIndexRequest>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const UpdateIndexRequest& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const UpdateIndexRequest& from) {
    UpdateIndexRequest::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(UpdateIndexRequest* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "UpdateIndexRequest";
  }
  protected:
  explicit UpdateIndexRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kVectorsFieldNumber = 1,
  };
  // repeated .VectorData vectors = 1;
  int vectors_size() const;
  private:
  int _internal_vectors_size() const;
  public:
  void clear_vectors();
  ::VectorData* mutable_vectors(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::VectorData >*
      mutable_vectors();
  private:
  const ::VectorData& _internal_vectors(int index) const;
  ::VectorData* _internal_add_vectors();
  public:
  const ::VectorData& vectors(int index) const;
  ::VectorData* add_vectors();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::VectorData >&
      vectors() const;

  // @@protoc_insertion_point(class_scope:UpdateIndexRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::VectorData > vectors_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_query_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// QueryRequest

// repeated float vector = 1;
inline int QueryRequest::_internal_vector_size() const {
  return _impl_.vector_.size();
}
inline int QueryRequest::vector_size() const {
  return _internal_vector_size();
}
inline void QueryRequest::clear_vector() {
  _impl_.vector_.Clear();
}
inline float QueryRequest::_internal_vector(int index) const {
  return _impl_.vector_.Get(index);
}
inline float QueryRequest::vector(int index) const {
  // @@protoc_insertion_point(field_get:QueryRequest.vector)
  return _internal_vector(index);
}
inline void QueryRequest::set_vector(int index, float value) {
  _impl_.vector_.Set(index, value);
  // @@protoc_insertion_point(field_set:QueryRequest.vector)
}
inline void QueryRequest::_internal_add_vector(float value) {
  _impl_.vector_.Add(value);
}
inline void QueryRequest::add_vector(float value) {
  _internal_add_vector(value);
  // @@protoc_insertion_point(field_add:QueryRequest.vector)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
QueryRequest::_internal_vector() const {
  return _impl_.vector_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
QueryRequest::vector() const {
  // @@protoc_insertion_point(field_list:QueryRequest.vector)
  return _internal_vector();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
QueryRequest::_internal_mutable_vector() {
  return &_impl_.vector_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
QueryRequest::mutable_vector() {
  // @@protoc_insertion_point(field_mutable_list:QueryRequest.vector)
  return _internal_mutable_vector();
}

// int32 k = 2;
inline void QueryRequest::clear_k() {
  _impl_.k_ = 0;
}
inline int32_t QueryRequest::_internal_k() const {
  return _impl_.k_;
}
inline int32_t QueryRequest::k() const {
  // @@protoc_insertion_point(field_get:QueryRequest.k)
  return _internal_k();
}
inline void QueryRequest::_internal_set_k(int32_t value) {
  
  _impl_.k_ = value;
}
inline void QueryRequest::set_k(int32_t value) {
  _internal_set_k(value);
  // @@protoc_insertion_point(field_set:QueryRequest.k)
}

// -------------------------------------------------------------------

// QueryResponse

// repeated int32 labels = 1;
inline int QueryResponse::_internal_labels_size() const {
  return _impl_.labels_.size();
}
inline int QueryResponse::labels_size() const {
  return _internal_labels_size();
}
inline void QueryResponse::clear_labels() {
  _impl_.labels_.Clear();
}
inline int32_t QueryResponse::_internal_labels(int index) const {
  return _impl_.labels_.Get(index);
}
inline int32_t QueryResponse::labels(int index) const {
  // @@protoc_insertion_point(field_get:QueryResponse.labels)
  return _internal_labels(index);
}
inline void QueryResponse::set_labels(int index, int32_t value) {
  _impl_.labels_.Set(index, value);
  // @@protoc_insertion_point(field_set:QueryResponse.labels)
}
inline void QueryResponse::_internal_add_labels(int32_t value) {
  _impl_.labels_.Add(value);
}
inline void QueryResponse::add_labels(int32_t value) {
  _internal_add_labels(value);
  // @@protoc_insertion_point(field_add:QueryResponse.labels)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
QueryResponse::_internal_labels() const {
  return _impl_.labels_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >&
QueryResponse::labels() const {
  // @@protoc_insertion_point(field_list:QueryResponse.labels)
  return _internal_labels();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
QueryResponse::_internal_mutable_labels() {
  return &_impl_.labels_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< int32_t >*
QueryResponse::mutable_labels() {
  // @@protoc_insertion_point(field_mutable_list:QueryResponse.labels)
  return _internal_mutable_labels();
}

// repeated float distances = 2;
inline int QueryResponse::_internal_distances_size() const {
  return _impl_.distances_.size();
}
inline int QueryResponse::distances_size() const {
  return _internal_distances_size();
}
inline void QueryResponse::clear_distances() {
  _impl_.distances_.Clear();
}
inline float QueryResponse::_internal_distances(int index) const {
  return _impl_.distances_.Get(index);
}
inline float QueryResponse::distances(int index) const {
  // @@protoc_insertion_point(field_get:QueryResponse.distances)
  return _internal_distances(index);
}
inline void QueryResponse::set_distances(int index, float value) {
  _impl_.distances_.Set(index, value);
  // @@protoc_insertion_point(field_set:QueryResponse.distances)
}
inline void QueryResponse::_internal_add_distances(float value) {
  _impl_.distances_.Add(value);
}
inline void QueryResponse::add_distances(float value) {
  _internal_add_distances(value);
  // @@protoc_insertion_point(field_add:QueryResponse.distances)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
QueryResponse::_internal_distances() const {
  return _impl_.distances_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
QueryResponse::distances() const {
  // @@protoc_insertion_point(field_list:QueryResponse.distances)
  return _internal_distances();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
QueryResponse::_internal_mutable_distances() {
  return &_impl_.distances_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
QueryResponse::mutable_distances() {
  // @@protoc_insertion_point(field_mutable_list:QueryResponse.distances)
  return _internal_mutable_distances();
}

// -------------------------------------------------------------------

// SetEfRequest

// int32 ef_search = 1;
inline void SetEfRequest::clear_ef_search() {
  _impl_.ef_search_ = 0;
}
inline int32_t SetEfRequest::_internal_ef_search() const {
  return _impl_.ef_search_;
}
inline int32_t SetEfRequest::ef_search() const {
  // @@protoc_insertion_point(field_get:SetEfRequest.ef_search)
  return _internal_ef_search();
}
inline void SetEfRequest::_internal_set_ef_search(int32_t value) {
  
  _impl_.ef_search_ = value;
}
inline void SetEfRequest::set_ef_search(int32_t value) {
  _internal_set_ef_search(value);
  // @@protoc_insertion_point(field_set:SetEfRequest.ef_search)
}

// -------------------------------------------------------------------

// SetEfResponse

// string status = 1;
inline void SetEfResponse::clear_status() {
  _impl_.status_.ClearToEmpty();
}
inline const std::string& SetEfResponse::status() const {
  // @@protoc_insertion_point(field_get:SetEfResponse.status)
  return _internal_status();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void SetEfResponse::set_status(ArgT0&& arg0, ArgT... args) {
 
 _impl_.status_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:SetEfResponse.status)
}
inline std::string* SetEfResponse::mutable_status() {
  std::string* _s = _internal_mutable_status();
  // @@protoc_insertion_point(field_mutable:SetEfResponse.status)
  return _s;
}
inline const std::string& SetEfResponse::_internal_status() const {
  return _impl_.status_.Get();
}
inline void SetEfResponse::_internal_set_status(const std::string& value) {
  
  _impl_.status_.Set(value, GetArenaForAllocation());
}
inline std::string* SetEfResponse::_internal_mutable_status() {
  
  return _impl_.status_.Mutable(GetArenaForAllocation());
}
inline std::string* SetEfResponse::release_status() {
  // @@protoc_insertion_point(field_release:SetEfResponse.status)
  return _impl_.status_.Release();
}
inline void SetEfResponse::set_allocated_status(std::string* status) {
  if (status != nullptr) {
    
  } else {
    
  }
  _impl_.status_.SetAllocated(status, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.status_.IsDefault()) {
    _impl_.status_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:SetEfResponse.status)
}

// int32 new_ef_search = 2;
inline void SetEfResponse::clear_new_ef_search() {
  _impl_.new_ef_search_ = 0;
}
inline int32_t SetEfResponse::_internal_new_ef_search() const {
  return _impl_.new_ef_search_;
}
inline int32_t SetEfResponse::new_ef_search() const {
  // @@protoc_insertion_point(field_get:SetEfResponse.new_ef_search)
  return _internal_new_ef_search();
}
inline void SetEfResponse::_internal_set_new_ef_search(int32_t value) {
  
  _impl_.new_ef_search_ = value;
}
inline void SetEfResponse::set_new_ef_search(int32_t value) {
  _internal_set_new_ef_search(value);
  // @@protoc_insertion_point(field_set:SetEfResponse.new_ef_search)
}

// -------------------------------------------------------------------

// VectorData

// int64 id = 1;
inline void VectorData::clear_id() {
  _impl_.id_ = int64_t{0};
}
inline int64_t VectorData::_internal_id() const {
  return _impl_.id_;
}
inline int64_t VectorData::id() const {
  // @@protoc_insertion_point(field_get:VectorData.id)
  return _internal_id();
}
inline void VectorData::_internal_set_id(int64_t value) {
  
  _impl_.id_ = value;
}
inline void VectorData::set_id(int64_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:VectorData.id)
}

// repeated float vector = 2;
inline int VectorData::_internal_vector_size() const {
  return _impl_.vector_.size();
}
inline int VectorData::vector_size() const {
  return _internal_vector_size();
}
inline void VectorData::clear_vector() {
  _impl_.vector_.Clear();
}
inline float VectorData::_internal_vector(int index) const {
  return _impl_.vector_.Get(index);
}
inline float VectorData::vector(int index) const {
  // @@protoc_insertion_point(field_get:VectorData.vector)
  return _internal_vector(index);
}
inline void VectorData::set_vector(int index, float value) {
  _impl_.vector_.Set(index, value);
  // @@protoc_insertion_point(field_set:VectorData.vector)
}
inline void VectorData::_internal_add_vector(float value) {
  _impl_.vector_.Add(value);
}
inline void VectorData::add_vector(float value) {
  _internal_add_vector(value);
  // @@protoc_insertion_point(field_add:VectorData.vector)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
VectorData::_internal_vector() const {
  return _impl_.vector_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
VectorData::vector() const {
  // @@protoc_insertion_point(field_list:VectorData.vector)
  return _internal_vector();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
VectorData::_internal_mutable_vector() {
  return &_impl_.vector_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
VectorData::mutable_vector() {
  // @@protoc_insertion_point(field_mutable_list:VectorData.vector)
  return _internal_mutable_vector();
}

// -------------------------------------------------------------------

// UpdateIndexRequest

// repeated .VectorData vectors = 1;
inline int UpdateIndexRequest::_internal_vectors_size() const {
  return _impl_.vectors_.size();
}
inline int UpdateIndexRequest::vectors_size() const {
  return _internal_vectors_size();
}
inline void UpdateIndexRequest::clear_vectors() {
  _impl_.vectors_.Clear();
}
inline ::VectorData* UpdateIndexRequest::mutable_vectors(int index) {
  // @@protoc_insertion_point(field_mutable:UpdateIndexRequest.vectors)
  return _impl_.vectors_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::VectorData >*
UpdateIndexRequest::mutable_vectors() {
  // @@protoc_insertion_point(field_mutable_list:UpdateIndexRequest.vectors)
  return &_impl_.vectors_;
}
inline const ::VectorData& UpdateIndexRequest::_internal_vectors(int index) const {
  return _impl_.vectors_.Get(index);
}
inline const ::VectorData& UpdateIndexRequest::vectors(int index) const {
  // @@protoc_insertion_point(field_get:UpdateIndexRequest.vectors)
  return _internal_vectors(index);
}
inline ::VectorData* UpdateIndexRequest::_internal_add_vectors() {
  return _impl_.vectors_.Add();
}
inline ::VectorData* UpdateIndexRequest::add_vectors() {
  ::VectorData* _add = _internal_add_vectors();
  // @@protoc_insertion_point(field_add:UpdateIndexRequest.vectors)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::VectorData >&
UpdateIndexRequest::vectors() const {
  // @@protoc_insertion_point(field_list:UpdateIndexRequest.vectors)
  return _impl_.vectors_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_query_2eproto
